services:
  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z

    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: adminpassword
    volumes:
      - ./data/minio:/data # Save data on drive

  cassandra:
    image: cassandra:5.0
    ports:
      - "9042:9042"
    environment:
      MAX_HEAP_SIZE: "512M"
      HEAP_NEWSIZE: "100M"
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  zookeeper:
    image: confluentinc/cp-zookeeper:4.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:4.0.0
    depends_on: [zookeeper]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 # Automatic topic creation